title: Geekyll Starter Blog
markdown: kramdown
url: ""
baseurl: "/geekyll-starter-blog"

# for atom feed
author:
  name: Sharad Raj
  email: iamsharadraj@gmail.com
  image: "https://avatars1.githubusercontent.com/u/36638057?s=460&u=b7ea83b7f3172f4517c653cefd5d0713853561b2&v=4"
  bio: Developed by <b>Sharad Raj</b> who lives in India building useful things for the world.
  github: "sharadcodes"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
