name: GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install APT dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git -y
          sudo apt-get install libudev-dev -y
          sudo apt-get install libusb-1.0-0-dev -y

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.12.0
          run_install: true

      - name: Build
        run: |
          npm run wallet:build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
